name: gatk4_calculatecontamination
description: Calculate the fraction of reads coming from cross-sample contamination
keywords:
  - gatk4
  - calculatecontamination
  - contamination
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - table:
      type: file
      description: Input table (results from GetPileupSummaries)
      pattern: "*.table"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - table:
      type: file
      description: Output table
      pattern: "*.table"

authors:
  - "@suzannejin"
